name: E2E Automation tests
on: 
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'target environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - stage
          - qa
jobs:
  android_tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16.15.1
        - name: Install dependencies
          run: npm install
        - name: Download feature files
          env: 
            IS_CLOUD_RUNNER: ${{ secrets.IS_CLOUD_RUNNER }}
          run: "npm run download_cucumber_features"
        - name: Test
          env: 
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            JIRA_CLOUD_CLIENT_ID: ${{ secrets.JIRA_CLOUD_ID }}
            JIRA_CLOUD_CLIENT_SECRET: ${{ secrets.JIRA_CLOUD_SECRET }}
          run: npx wdio test/config/android.bs.conf.js
        - name: Create Test Execution
          run: "npm run submit_cucumber_results"

