name: E2E Automation tests
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'target environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - stage
          - qa
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.15.1
        - name: Install
          run: npm install
        - name: Test
          env: 
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            $JIRA_CLOUD_CLIENT_ID: ${{ secrets.JIRA_CLOUD_ID }}
            $JIRA_CLOUD_CLIENT_SECRET: ${{ secrets.JIRA_CLOUD_SECRET }}
          run: npx wdio test/config/android.bs.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
